---
deployment:
  tasks:
    - /bin/mkdir -p $HOME/public_html && /usr/bin/rsync -av --exclude='.git' --exclude='.gitignore' --exclude='.cpanel.yml' --exclude='config.php' --exclude='admin/config.php' --exclude='uploads/' --exclude='admin/uploads/' ./ $HOME/public_html/
